apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.2
    releaseName: istio-base
    namespace: istio-system

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.2
    releaseName: istiod
    namespace: istio-system

  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.2
    releaseName: istio-ingressgateway
    namespace: istio-system
