apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
  namespace: local-rate-limit
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"https://docker.io":{"auth":""}}}'